# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'sdk/databox/Azure.Management.DataBox/src/Azure.Management.DataBox.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'sdk/databox/Azure.Management.DataBox/src/Azure.Management.DataBox.csproj'
    arguments: '/t:GenerateCode'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'sdk/databox/Azure.Management.DataBox/src/Azure.Management.DataBox.csproj'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dll'
    publishLocation: 'Container'

- task: CmdLine@2
  inputs:
    script: |
      git config --global user.email "t-vajana@microsoft.com"
      git config --global user.name "Vaishnavi Janardhan"

      echo GIT CHECKOUT
      git checkout master
      echo GIT STATUS
      git status
      echo GIT ADD
      git add .
      echo GIT STATUS
      git status
      echo GIT COMMIT
      git commit -m "Generate models for DataBox"
      echo GIT PUSH
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin master    