# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'sdk/databox/Azure.Management.DataBox/src/Azure.Management.DataBox.csproj'

# Currently doesn't take the fix to autorest.csharp
# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'build'
#     projects: 'sdk/databox/Azure.Management.DataBox/src/Azure.Management.DataBox.csproj'
#     arguments: '/t:GenerateCode'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'npx autorest@https://github.com/Azure/autorest/releases/download/autorest-3.0.6222/autorest-3.0.6222.tgz --version=3.0.6282 sdk/databox/Azure.Management.DataBox/src/autorest.md  --use=https://github.com/Azure/autorest.csharp/releases/download/3.0.0-dev.20200622.3/autorest-csharp-v3-3.0.0-dev.20200622.3.tgz --output-folder=sdk/databox/Azure.Management.DataBox/src --title=Azure.Management.DataBox --namespace=Azure.Management.DataBox --shared-source-folder=eng/../sdk/core/Azure.Core/src/Shared/'
    projects: 'sdk/databox/Azure.Management.DataBox/src/Azure.Management.DataBox.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'sdk/databox/Azure.Management.DataBox/src/Azure.Management.DataBox.csproj'
    
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'artifacts/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'    

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dll'
    publishLocation: 'Container'

- task: CmdLine@2
  inputs:
    script: |
      git config --global user.email "t-vajana@microsoft.com"
      git config --global user.name "Vaishnavi Janardhan"

      echo GIT CHECKOUT
      git checkout master
      echo GIT STATUS
      git status
      echo GIT ADD
      git add .
      echo GIT STATUS
      git status
      echo GIT COMMIT
      git commit -m "Generate SDK for DataBox"
      echo GIT PUSH
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin master    