# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'sdk/databox/Azure.Management.DataBox/src/Azure.Management.DataBox.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'sdk/databox/Azure.Management.DataBox/src/Azure.Management.DataBox.csproj'
    arguments: '/t:GenerateCode'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'sdk/databox/Azure.Management.DataBox/src/Azure.Management.DataBox.csproj'    