stages:
- stage: Check
  jobs:
  - job: ValidatePipeline
    pool: server

- stage: Build
  jobs:
  - job: BuildPackages
    pool: server

- stage: Test
  dependsOn: Build
  jobs:
  - job: UnitTest
    pool: server

  - job: SmokeTest
    dependsOn: UnitTest
    pool: server

  - job: LiveTest
    dependsOn: SmokeTest
    pool: server

- stage: PublishPreview
  dependsOn: Test
  jobs:
  - ${{each artifact in parameters.Artifacts}}
    pool: server

